language: node_js

sudo: false
dist: trusty

git:
  depth: 3

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

notifications:
  email: false
  slack:
    secure: OBJPAZvEEXYXMPXvUYn1brURINUvJnuPX1ZKIElDM0XUDWD21F2GLT19dPMCZJr3qxRi1GPQm34SktX4SrbAXsA9a/jyTjH4L63EAcCwHjgtvgkdalfi6YLwU3pk3Upao+CnBFnBHe+grynRVGre/KR61DYKCm/OldQFUcS1dwKgdF2QpTgcpFGaVAJNJbWBRRxAnZpdG9YltLuTzkNocTOE5G7PUCaoRjoTxKumiTK5IhbuvCGwW93xCgf1lZGSR9eqGQQHgky+jFzKDe2gNdQp/OwI5NN5x28d0b48AnH6DrdXVDb/2WBKKDfszCXIwm4a3BYKBxgamvJn1ly/nZMe3NOd3Pp2pH2AT7dOTbXEXLMXgw6WPfR/6AIIzOMyt63cJz0yB1mIGF09sXW3BrkvinREp/a5/w8Q8cQzrRgC6f7NQ3E4b5QFT11+dP2U038TEZUVy6ghUGg03OnIUPPJPxYyRoaVTal9y3Sey7x7Eio5/JD87oqob5ohZv/Ol6aV715vThR81mE/CoyERXVa0iP3hW2D1nK7PN2xPc3GZZtmYZi6UtBTc9pAMHQooo3P0NVMyCUySjnSCFxRQfvf2Y1bgBWtoQQ3I7VmRzrJGMv/QrEXeqP+WYNMkFOOsB0VuPi1R3pO2vr8xro2Xw3JPFKdzoEyee51uev5KgY=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache: yarn

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: test
    if: branch = master and tag IS blank and type IN (pull_request, api)

before_script:
  - bash bin/prepare.sh

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash bin/check/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash bin/check/phpmd.sh

    - stage: test
      language: php
      php: '7.2'
      script: bash bin/test/phpunit.sh
    - stage: test
      language: php
      php: '7.3'
      script: bash bin/test/phpunit.sh
